import { AuthProvider } from "@/context/AuthContext";
import "./globals.css";
import { NextUIProvider } from "@nextui-org/react";

export const metadata = {
  title: "Aplikasi Reservasi Pasien",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="id" className="scroll-smooth scrollbar-hide">
      <AuthProvider>
        <body>
          <NextUIProvider>{children}</NextUIProvider>
        </body>
      </AuthProvider>
    </html>
  );
}
